<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.playwrightjava</groupId>
    <artifactId>PlaywrightFramework</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- Add allure-bom to dependency management to ensure correct versions of all the dependencies are used -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-bom</artifactId>
                <version>${allure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
<!--Playwright dependency-->
        <!-- Source: https://mvnrepository.com/artifact/com.microsoft.playwright/playwright -->
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.61.0</version>
            <scope>compile</scope>
        </dependency>
        <!-- Add necessary Allure dependencies to dependencies section -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <scope>test</scope>
        </dependency>
<!--        Add necessary Allure Playwright dependencies-->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-playwright</artifactId>
            <scope>test</scope>
        </dependency>
<!--TestNG dependency-->
        <!-- Source: https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.12.0</version>
            <scope>test</scope>
        </dependency>

<!--JSON Path dependency-->
        <!-- Source: https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path -->
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>3.0.0</version>
            <scope>compile</scope>
        </dependency>
<!--TestNG engine for JUnit platform-->
        <!-- Source: https://mvnrepository.com/artifact/org.junit.support/testng-engine -->
        <dependency>
            <groupId>org.junit.support</groupId>
            <artifactId>testng-engine</artifactId>
            <version>1.1.0</version>
            <scope>test</scope>
        </dependency>


    </dependencies>


<!--    Creating different profiles,  -->
    <profiles>
<!--        Regression profile   to run:  mvn test -PRegression-->
        <profile>
            <id>Regression</id>
            <build>
                <!--        Maven sure fire plugin-->
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
<!--                        <version>3.5.2</version>-->
                        <version>3.6.0</version>
                    </plugin>
                </plugins>
            </build>
        </profile>

<!--        Smoke profile,  to run:  mvn test -PSmoke-->
        <profile>
            <id>Smoke</id>
            <build>
                <!--        Maven sure fire plugin-->
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
<!--                        <version>3.5.2</version>-->
                        <version>3.6.0</version>
                        <configuration>
                            <groups>smoke</groups>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

<!--        setting env variables from maven command example-->
        <profile>
            <id>Framework</id>
            <build>
                <!--        Maven sure fire plugin-->
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
<!--                        <version>3.5.2</version>-->
                        <version>3.6.0</version>
                        <configuration>
                            <groups>framework</groups>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- Define the version of Allure you want to use via the allure.version property -->
        <allure.version>2.35.3</allure.version>
    </properties>

</project>